<a href="https://colab.research.google.com/github/Tensai-Pro/SRI-PracticeTasks/blob/master/PyTorch%20NN/1)%20RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
from torch import nn

import numpy as np

In [ ]:
text = ['hey how are you','good i am fine','have a nice day']

In [ ]:
chars = set(' '.join(text))
chars

{' ',
 'a',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'm',
 'n',
 'o',
 'r',
 'u',
 'v',
 'w',
 'y'}

In [ ]:
int2char = dict(enumerate(chars))
int2char

{0: 'o',
 1: 'w',
 2: 'u',
 3: 'a',
 4: 'r',
 5: 'h',
 6: 'i',
 7: 'f',
 8: 'd',
 9: 'n',
 10: 'y',
 11: 'g',
 12: 'v',
 13: 'c',
 14: 'e',
 15: ' ',
 16: 'm'}

In [ ]:
char2int = {char: id for id, char in int2char.items()}
char2int

{'o': 0,
 'w': 1,
 'u': 2,
 'a': 3,
 'r': 4,
 'h': 5,
 'i': 6,
 'f': 7,
 'd': 8,
 'n': 9,
 'y': 10,
 'g': 11,
 'v': 12,
 'c': 13,
 'e': 14,
 ' ': 15,
 'm': 16}

In [ ]:
maxlen = len(max(text, key=len))
maxlen

15

In [ ]:
# Paddings sequences to be equal length
for i in range(len(text)):
  while len(text[i]) != maxlen:
    text[i] += ' '

text

['hey how are you', 'good i am fine ', 'have a nice day']

In [ ]:
# Input data — each character in the sequence (excluding the last one)
# Target data — one time-step ahead of the input char (excluding the first one)
input_seq = []
target_seq = []

for i in range(len(text)):
  input_seq.append(text[i][:-1])

  target_seq.append(text[i][1:])

  print(f'Input sequence: {input_seq[i]}\nTarget sequence: {target_seq[i]}\n')

Input sequence: hey how are yo
Target sequence: ey how are you

Input sequence: good i am fine
Target sequence: ood i am fine 

Input sequence: have a nice da
Target sequence: ave a nice day



In [ ]:
print(input_seq)
print(target_seq)

['hey how are yo', 'good i am fine', 'have a nice da']
['ey how are you', 'ood i am fine ', 'ave a nice day']


In [ ]:
# Transforming into integers
for i in range(len(text)):
  input_seq[i] = [char2int[char] for char in input_seq[i]]
  target_seq[i] = [char2int[char] for char in target_seq[i]]

print(input_seq)
print(target_seq)

[[5, 14, 10, 15, 5, 0, 1, 15, 3, 4, 14, 15, 10, 0], [11, 0, 0, 8, 15, 6, 15, 3, 16, 15, 7, 6, 9, 14], [5, 3, 12, 14, 15, 3, 15, 9, 6, 13, 14, 15, 8, 3]]
[[14, 10, 15, 5, 0, 1, 15, 3, 4, 14, 15, 10, 0, 2], [0, 0, 8, 15, 6, 15, 3, 16, 15, 7, 6, 9, 14, 15], [3, 12, 14, 15, 3, 15, 9, 6, 13, 14, 15, 8, 3, 10]]


In [ ]:
# number of unique chars
dict_size = len(char2int)
# length of the longest sentence in the dataset minus one because we deleted one char
seq_len = maxlen - 1
# number of elements in dataset (number of sentences)
batch_size = len(text)

def one_hot_encode(sequence, dict_size, seq_len, batch_size):
  features = np.zeros((batch_size, seq_len, dict_size), dtype=np.float32)

  for i in range(batch_size):
    for j in range(seq_len):
      features[i, j, sequence[i][j]] = 1

  return features

In [ ]:
input_seq = one_hot_encode(input_seq, dict_size, seq_len, batch_size)

In [ ]:
print(input_seq.shape)
print(input_seq[0].shape)

(3, 14, 17)
(14, 17)


In [ ]:
print(type(target_seq))
print(target_seq)

print(type(input_seq))
print(input_seq)

<class 'list'>
[[14, 10, 15, 5, 0, 1, 15, 3, 4, 14, 15, 10, 0, 2], [0, 0, 8, 15, 6, 15, 3, 16, 15, 7, 6, 9, 14, 15], [3, 12, 14, 15, 3, 15, 9, 6, 13, 14, 15, 8, 3, 10]]
<class 'numpy.ndarray'>
[[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [ ]:
# Moving data to torch
input_seq = torch.from_numpy(input_seq)
target_seq = torch.Tensor(target_seq)

In [ ]:
# Checking if we can use CPU or GPU
is_cuda = torch.cuda.is_available()

if is_cuda:
  device = torch.device('cuda')
  print('GPU is available')
else:
  device = torch.device('cpu')
  print('GPU is not available, CPU is used')

GPU is not available, CPU is used


# Building a model

In [ ]:
class Model(nn.Module):
  def __init__(self, input_size, output_size, hidden_dim, n_layers):
    super(Model, self).__init__()

    # Defining some parameters
    self.hidden_dim = hidden_dim
    self.n_layers = n_layers

    # Defining layers
    # RNN layer
    self.rnn = nn.RNN(input_size, hidden_dim, n_layers, batch_first=True)
    # Fully connected layer
    self.fc = nn.Linear(hidden_dim, output_size)

  def forward(self, x):
    batch_size = x.size(0)  # like .shape in numpy

    # Initializing hidden state for first input using method defined below
    hidden = self.init_hidden(batch_size)

    # Passing in the input and hidden state into the model and obtaining outputs
    output, hidden = self.rnn(x, hidden)

    # Reshaping the outputs such that it can be fit into the fully connected layer
    output = output.contiguous().view(-1, self.hidden_dim)
    output = self.fc(output)

    return output.to(device), hidden.to(device)

  def init_hidden(self, batch_size):
    # This method generates the first initial hidden state of zeros
    hidden = torch.zeros(self.n_layers, batch_size, self.hidden_dim).to(device)
    return hidden

In [ ]:
model = Model(input_size=dict_size, output_size=dict_size, hidden_dim=12, n_layers=1)
model.to(device)

n_epochs = 100
lr = 0.01

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=lr)

In [ ]:
# Training
for epoch in range(1, n_epochs + 1):
  optimizer.zero_grad()   # to clear existing gradients from previous epoch
  input_seq.to(device)
  output, hidden = model(input_seq)
  loss = criterion(output, target_seq.view(-1).long().to(device))
  loss.backward()   # Does backpropagation and calculates gradients
  optimizer.step() # Updates weights accordingly

  if epoch % 10 == 0:
    print(f'Epoch: {epoch}/{n_epochs}............', end=' ')
    print('Loss: {:.4f}'.format(loss.item()))
    print(output.size())
    print(hidden.size())
    print('\n')

Epoch: 10/100............ Loss: 2.3642
torch.Size([42, 17])
torch.Size([1, 3, 12])


Epoch: 20/100............ Loss: 2.0115
torch.Size([42, 17])
torch.Size([1, 3, 12])


Epoch: 30/100............ Loss: 1.5866
torch.Size([42, 17])
torch.Size([1, 3, 12])


Epoch: 40/100............ Loss: 1.2033
torch.Size([42, 17])
torch.Size([1, 3, 12])


Epoch: 50/100............ Loss: 0.8818
torch.Size([42, 17])
torch.Size([1, 3, 12])


Epoch: 60/100............ Loss: 0.6213
torch.Size([42, 17])
torch.Size([1, 3, 12])


Epoch: 70/100............ Loss: 0.4331
torch.Size([42, 17])
torch.Size([1, 3, 12])


Epoch: 80/100............ Loss: 0.3070
torch.Size([42, 17])
torch.Size([1, 3, 12])


Epoch: 90/100............ Loss: 0.2272
torch.Size([42, 17])
torch.Size([1, 3, 12])


Epoch: 100/100............ Loss: 0.1762
torch.Size([42, 17])
torch.Size([1, 3, 12])




In [ ]:
def predict(model, character):
  char = np.array([[char2int[c] for c in character]])
  print(char)
  print(char.shape)
  char = one_hot_encode(char, dict_size, char.shape[1], 1)
  print(char)
  char = torch.from_numpy(char)
  print(char)
  char = char.to(device)

  out, hidden = model(char)
  print(f'\n\nout: {out.size()}')
  print(f'\n\nout: {out}')
  print(f'\n\nhidden: {hidden.size()}')

  prob = nn.functional.softmax(out[-1], dim=0).data
  print('\n\nprob: ', prob.size())
  char_ind = torch.max(prob, dim=0)
  print('char_ind:', char_ind)
  char_ind = char_ind[1].item()
  print(char_ind)

  return int2char[char_ind], hidden

In [ ]:
def sample(model, out_len, start='hey'):
  model.eval()

  start = start.lower()
  chars = [ch for ch in start]
  size = out_len - len(chars)

  for _ in range(size):
    char, h = predict(model, chars)
    chars.append(char)

  return ''.join(chars)

In [ ]:
sample(model, 15, 'fine')

[[ 7  6  9 14]]
(1, 4)
[[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]]
tensor([[[0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]]])


out: torch.Size([4, 17])


out: tensor([[ 1.2409, -0.4594,  0.0093,  2.9914, -0.6101, -1.9193,  3.8929, -1.5244,
          0.3018, -0.1482, -2.0354, -1.4850, -2.4908, -1.4812,  2.4166,  1.0444,
         -2.3679],
        [-2.7303,  1.1688,  1.1848, -1.8834,  0.8888,  1.0730,  0.6687, -2.2983,
          2.2619,  3.2910,  1.9122, -0.5168,  3.4853,  2.1055, -1.9282, -0.7284,
          0.9732],
        [ 1.2756,  0.1941, -4.5308,  2.94

'fine a nice day'